# Generated by Django 3.2.7 on 2021-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211010_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='bids',
        ),
        migrations.AddField(
            model_name='auctions',
            name='item_bids',
            field=models.ManyToManyField(null=True, related_name='bids', to='auctions.Bid'),
        ),
    ]
