# Generated by Django 3.2.7 on 2021-10-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211010_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='item_bids',
            new_name='item_bid',
        ),
    ]
