# Generated by Django 3.2.7 on 2021-10-26 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211026_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctions'),
        ),
    ]
