# Generated by Django 3.2.7 on 2021-10-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comments_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(choices=[('a', 'Clothing'), ('b', 'Furniture'), ('c', 'Electronics'), ('d', 'Toys'), ('e', 'Books'), ('f', 'Other')], default='Other', max_length=1),
        ),
    ]
