# Generated by Django 3.2.7 on 2021-10-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='last_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_bid_for_the_auction', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(choices=[('a', 'Clothing'), ('b', 'Showpiece'), ('c', 'Electronics'), ('d', 'Toys'), ('e', 'Books'), ('f', 'Other')], default='Other', max_length=10),
        ),
    ]
