# Generated by Django 3.2.7 on 2021-10-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211028_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(choices=[('a', 'Clothing'), ('b', 'Showpiece'), ('c', 'Electronics'), ('d', 'Toys'), ('e', 'Books'), ('f', 'Other')], default='Other', max_length=25),
        ),
    ]
