# Generated by Django 3.2.7 on 2021-10-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auctions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(default='Other', max_length=10),
        ),
    ]
